export default {
    'ERROR':'ERROR',
    'USER_LOGIN':'USER_LOGIN',
    'USER_LOGINOUT':'USER_LOGINOUT',
    'USER_GET':'USER_GET',
    'CATES':'CATES',
    'CATE_ADD':'CATE_ADD',
    'CATE_DELETE':'CATE_DELETE',
    'CATE_UPDATE':'CATE_UPDATE',
    'CATE_STATE_UPDATE':'CATE_STATE_UPDATE',
    'MATERIALS':'MATERIALS',
    'MATERIAL_ADD':'MATERIAL_ADD',
    'MATERIAL_GET':'MATERIAL_GET',
    'MATERIAL_UPDATE':'MATERIAL_UPDATE',
    'MATERIAL_DELETE':'MATERIAL_DELETE',
    'MATERIAL_STATE_UPDATE':'MATERIAL_STATE_UPDATE'
}